// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwgGh_Igu_Q4nhHc9zJneFxc1taEhr3SI',
    appId: '1:624090640531:web:c1eec159253e7101541d66',
    messagingSenderId: '624090640531',
    projectId: 'whatsapp-clone-ff0e0',
    authDomain: 'whatsapp-clone-ff0e0.firebaseapp.com',
    storageBucket: 'whatsapp-clone-ff0e0.firebasestorage.app',
    measurementId: 'G-SLRBF86V8B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOtTqszZQ6Wj-hNOgEK5u5QIy5q8UqM88',
    appId: '1:624090640531:android:f0e2ceae83909d58541d66',
    messagingSenderId: '624090640531',
    projectId: 'whatsapp-clone-ff0e0',
    storageBucket: 'whatsapp-clone-ff0e0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGssVNFvNdwfFXZqjXnJH_pciadVf7l_k',
    appId: '1:624090640531:ios:c25adab9558a42bb541d66',
    messagingSenderId: '624090640531',
    projectId: 'whatsapp-clone-ff0e0',
    storageBucket: 'whatsapp-clone-ff0e0.firebasestorage.app',
    iosBundleId: 'com.example.whatsapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGssVNFvNdwfFXZqjXnJH_pciadVf7l_k',
    appId: '1:624090640531:ios:c25adab9558a42bb541d66',
    messagingSenderId: '624090640531',
    projectId: 'whatsapp-clone-ff0e0',
    storageBucket: 'whatsapp-clone-ff0e0.firebasestorage.app',
    iosBundleId: 'com.example.whatsapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwgGh_Igu_Q4nhHc9zJneFxc1taEhr3SI',
    appId: '1:624090640531:web:d19fdb3fca521e81541d66',
    messagingSenderId: '624090640531',
    projectId: 'whatsapp-clone-ff0e0',
    authDomain: 'whatsapp-clone-ff0e0.firebaseapp.com',
    storageBucket: 'whatsapp-clone-ff0e0.firebasestorage.app',
    measurementId: 'G-XWGVQ9C5C1',
  );
}
